// war3map.j boilerplate generator. Mirrors what the World Editor emits for
// config()/main() (observed in real campaign scripts; natives/BJs checked against
// the 3.0.0.24268 common.j / blizzard.j from https://github.com/Luashine/jass-history).

import { CELL } from './formats.ts';

/** JASS string literal. */
function str(s) {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r?\n/g, '|n') + '"';
}

// JASS real literal. Up to 4 decimals, never exponent notation. (Was toFixed(1): turned the
// 0.04 s tick timer into 0.0 — regression test in test/jass.test.js.)
function real(v) {
  let s = Number(v).toFixed(4).replace(/0+$/, '');
  if (s.endsWith('.')) s += '0';
  return s === '-0.0' ? '0.0' : s;
}

const CONTROL = { user: 'MAP_CONTROL_USER', computer: 'MAP_CONTROL_COMPUTER', neutral: 'MAP_CONTROL_NEUTRAL', rescuable: 'MAP_CONTROL_RESCUABLE' };
const RACE = { human: 'RACE_PREF_HUMAN', orc: 'RACE_PREF_ORC', undead: 'RACE_PREF_UNDEAD', nightelf: 'RACE_PREF_NIGHTELF' };

/**
 * @param {object} o
 * @param {string} o.name
 * @param {string} [o.description]
 * @param {number} o.width cells
 * @param {number} o.height cells
 * @param {number[]} [o.boundary] [left,right,bottom,top]
 * @param {{id:number,control:string,race:string,color?:number,x:number,y:number,team:number}[]} o.players
 * @param {string} [o.globals] extra globals block lines
 * @param {string} [o.functions] user functions (placed before main)
 * @param {string} [o.init] statements run at the end of main()
 * @param {string} [o.tilesetDnc] day/night model set, default Lordaeron
 */
function buildScript(o) {
  const b = o.boundary || [6, 6, 4, 8];
  const left = -o.width * CELL / 2 + b[0] * CELL;
  const right = o.width * CELL / 2 - b[1] * CELL;
  const bottom = -o.height * CELL / 2 + b[2] * CELL;
  const top = o.height * CELL / 2 - b[3] * CELL;
  const players = o.players;
  const teams = [...new Set(players.map((p) => p.team))];

  const L = [];
  L.push('//===========================================================================');
  L.push('// Generated by warcraft-dune build pipeline. Do not edit by hand.');
  L.push('//===========================================================================');
  L.push('globals');
  if (o.globals) L.push(o.globals);
  L.push('endglobals');
  L.push('');
  if (o.functions) L.push(o.functions, '');

  L.push('function InitCustomPlayerSlots takes nothing returns nothing');
  players.forEach((p, i) => {
    L.push(`    call SetPlayerStartLocation( Player(${p.id}), ${i} )`);
    L.push(`    call ForcePlayerStartLocation( Player(${p.id}), ${i} )`);
    L.push(`    call SetPlayerColor( Player(${p.id}), ConvertPlayerColor(${p.color != null ? p.color : p.id}) )`);
    L.push(`    call SetPlayerRacePreference( Player(${p.id}), ${RACE[p.race || 'human']} )`);
    L.push(`    call SetPlayerRaceSelectable( Player(${p.id}), false )`);
    L.push(`    call SetPlayerController( Player(${p.id}), ${CONTROL[p.control]} )`);
  });
  L.push('endfunction', '');

  L.push('function InitCustomTeams takes nothing returns nothing');
  teams.forEach((t) => {
    const members = players.filter((p) => p.team === t);
    members.forEach((p) => L.push(`    call SetPlayerTeam( Player(${p.id}), ${t} )`));
    for (const a of members) for (const c of members) {
      if (a !== c) L.push(`    call SetPlayerAllianceStateAllyBJ( Player(${a.id}), Player(${c.id}), true )`);
    }
  });
  L.push('endfunction', '');

  L.push('function main takes nothing returns nothing');
  L.push(`    call SetCameraBounds( ${real(left)} + GetCameraMargin(CAMERA_MARGIN_LEFT), ${real(bottom)} + GetCameraMargin(CAMERA_MARGIN_BOTTOM), ${real(right)} - GetCameraMargin(CAMERA_MARGIN_RIGHT), ${real(top)} - GetCameraMargin(CAMERA_MARGIN_TOP), ${real(left)} + GetCameraMargin(CAMERA_MARGIN_LEFT), ${real(top)} - GetCameraMargin(CAMERA_MARGIN_TOP), ${real(right)} - GetCameraMargin(CAMERA_MARGIN_RIGHT), ${real(bottom)} + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )`);
  const dnc = o.tilesetDnc || 'Lordaeron';
  L.push(`    call SetDayNightModels( ${str(`Environment\\DNC\\DNC${dnc}\\DNC${dnc}Terrain\\DNC${dnc}Terrain.mdl`)}, ${str(`Environment\\DNC\\DNC${dnc}\\DNC${dnc}Unit\\DNC${dnc}Unit.mdl`)} )`);
  L.push('    call NewSoundEnvironment( "Default" )');
  if (o.ambientDay) L.push(`    call SetAmbientDaySound( ${str(o.ambientDay)} )`);
  if (o.ambientNight) L.push(`    call SetAmbientNightSound( ${str(o.ambientNight)} )`);
  L.push('    call SetMapMusic( "Music", true, 0 )');
  L.push('    call InitBlizzard(  )');
  if (o.init) L.push(o.init);
  L.push('endfunction', '');

  L.push('function config takes nothing returns nothing');
  L.push(`    call SetMapName( ${str(o.name)} )`);
  L.push(`    call SetMapDescription( ${str(o.description || '')} )`);
  L.push(`    call SetPlayers( ${players.length} )`);
  L.push(`    call SetTeams( ${teams.length} )`);
  L.push('    call SetGamePlacement( MAP_PLACEMENT_USE_MAP_SETTINGS )');
  players.forEach((p, i) => L.push(`    call DefineStartLocation( ${i}, ${real(p.x)}, ${real(p.y)} )`));
  L.push('    call InitCustomPlayerSlots(  )');
  L.push('    call InitCustomTeams(  )');
  L.push('endfunction', '');
  return L.join('\r\n');
}

export { buildScript, str, real };
